### ISSUE TITLE
erreur a discuter ensemble si possible par téléphone

### ISSUE THREAD

**Issue by yann-mael** [Delegation-numerique-en-sante/mesconseilscovid#111]
Il y a une erreur à la question 8 "mes contacts récent"

si je coche je n’était dans aucune de ces situation:
on ne devrais pas conseiller l'isolement (message de statut et premier message personalisé)
mais dire : vous avez passé du temps avec quelqu'un de positif mais il ne s'agit pas a priori d'un contact a risque, au moindre doute ou en cas d’apparition de symptôme contacter votre médecin.
et enchaîner sur les conseils comme quelqu’un qui a répondu non a la question 8

**Comment by davidbgk** [comment]
@yann-mael qu'en est-il si l’utilisateur·ice a coché plusieurs sous-cases ?

**Comment by yann-mael** [comment]
les autres cases l'emportent par rapport a "aucune de ces situation"

**Comment by davidbgk** [comment]
Ajout d'un bloc « Vos contacts à risque » en haut de la page avec illustration dédiée en gardant le statut vert.

**Comment by davidbgk** [comment]
Réalisé dans https://github.com/Delegation-numerique-en-sante/mesconseilscovid/pull/152
