### ISSUE TITLE
changement rouge/orange

### ISSUE THREAD

**Issue by yann-mael** [Delegation-numerique-en-sante/mesconseilscovid#117]
comme il n'y a plus de département en rouge,

je propose de changer le nom des fichier rouge par orange ainsi que dans le desriptif (fichier readme partie critères/couleurs)

Hela a trouver la nouvelle carte des données de département

Je change les texte du fichier conseils_département_rouge.md, il faudra changer le titre en orange

**Comment by ronnix** [comment]
Fait dans 93a603890f5310ae70aab5c643a04a9fdb67ef90
