### ISSUE TITLE
ajout d'une case a cocher dans Contact à risque : a faire mardi 

### ISSUE THREAD

**Issue by yann-mael** [Delegation-numerique-en-sante/mesconseilscovid#133]
dans Contact à risque

ajouter une sous question : "j'ai été informé par mon application Stopcovid que j'ai eu un contact à risque avec une personne testée positive au Covid-19"

si la personne coche cette case : même fin que les autres sous question (hors case aucune de ces situation)

**Comment by davidbgk** [comment]
Ajouté dans https://github.com/Delegation-numerique-en-sante/mesconseilscovid/pull/142
