### ISSUE TITLE
Incohérence dans l'isolement et le dépistage des cas contacts vaccinés

### ISSUE THREAD

**Issue by Aymerik** [Delegation-numerique-en-sante/mesconseilscovid#1356]
Bonjour,

J'ai repéré quelques incohérences sur le dépistage et l'isolement (ou non) des cas contacts complètement vaccinés.

Le formulaire personnalisé indique qu'il n'est nécessaire ni de se faire tester, ni de s'isoler : 
![image](https://user-images.githubusercontent.com/15689805/126906307-58c77224-ebb2-47db-a201-3f4a17989fb9.png)

La page [Je suis vacciné](https://mesconseilscovid.sante.gouv.fr/je-suis-vaccine.html) indique qu'il faut se faire tester et s'isoler : 
![image](https://user-images.githubusercontent.com/15689805/126906341-f5a8ba01-4d64-4796-bca9-00f32e1ab30b.png)

La page [Je suis cas contact](https://mesconseilscovid.sante.gouv.fr/cas-contact-a-risque.html) indique qu'il faut faire un test mais qu'il n'est pas nécessaire de s'isoler (sauf si test positif)
![image](https://user-images.githubusercontent.com/15689805/126906432-17e1030b-9a4a-4aec-b55a-ec1ffe3cb750.png)

Merci

**Comment by davidbgk** [comment]
Bonjour @Aymerik, merci beaucoup d'avoir remonté cette incohérence 🙇. C'est maintenant corrigé et déployé !
