### ISSUE TITLE
Fin du support de IE11 👋 

### ISSUE THREAD

**Issue by davidbgk** [Delegation-numerique-en-sante/mesconseilscovid#1998]
## Check-list
- [x] Envoyer le [courriel à Microsoft](https://docs.microsoft.com/fr-fr/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection)
- [x] [Commentaires conditionnels](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537512(v=vs.85)?redirectedfrom=MSDN) pour afficher une bannière 
- [x] Enlever les polyfills `details/summary`, `custom_event`
- [x] Vérifier que l'on fait pas des trucs spécifiques dans les events
- [ ] Vérifier si les `Array.from` sont encore nécessaires
- [ ] Enlever les imports de `core-js` devenus obsolètes
- [x] Réajuster la browserlist => `since 2016` ou `supports es6-class` (avec `and not IE > 0` ?), ne pas oublier d'aller repêcher de vieux Safari par exemple
- [ ] Utilisation de `<template>` ?
- [ ] Réduire la CSS ? (fouiller les messages de commits)
- [ ] Vérifier l'utilité du datepicker
- [ ] D'autres choses ?

**Comment by rik** [comment]
Concernant le courriel, nous avons la [confirmation qu'il n'y a pas besoin d'avoir de bannières](https://github.com/MicrosoftDocs/edge-developer/issues/1718).

**Comment by davidbgk** [comment]
L'envoi du courriel a été fait ce jour 📬

**Comment by davidbgk** [comment]
> We have submit your request to have the following sites added to the Need Microsoft Edge List. 
> When a domain is added to the list, it will be applied to all subdomains or paths.  The reference number is 38110959.
> We will follow up once the list has been updated.

Rapide !

**Comment by davidbgk** [comment]
Envoyé ce jour :

> Any news on the update of the list?
>
> The web site says that it’s usually updated within a week, and it's been more than two weeks now.

**Comment by davidbgk** [comment]
Réponse rapide et personnelle :

> Sorry, we’ve had multiple delays.  We actually still need to process requests from December. 
 >
> I currently don’t have an ETA but we will keep you posted.  If you prefer to monitor for the update here is the link to the Need Microsoft Edge list: [https://edge.microsoft.com/neededge/v1](https://edge.microsoft.com/neededge/v1)

**Comment by davidbgk** [comment]
> Thanks for your patience!  The sites have been added to the Need Microsoft Edge list.  Here is the link for verification: https://edge.microsoft.com/neededge/v1 (version 69+).  The update is deployed by region and it might take up to 24 hours to see the changes.

🎉

**Comment by rik** [comment]
```
$ curl https://edge.microsoft.com/neededge/v1 | grep mesconseilscovid.sante.gouv.fr && echo "Youpi !" || echo "Pas encore…"
Youpi !
```

**Comment by ronnix** [comment]
J’ai testé dans une VM et la redirection vers Edge fonctionne une fois qu’il a mis à jour sa liste en arrière-plan...

**Comment by rik** [comment]
Est-ce que les stats IE11 ont été impactées ? Après [l'ajout de la bannière](https://github.com/Delegation-numerique-en-sante/mesconseilscovid/pull/2002) ? Après l'ajout par Microsoft ?

**Comment by ronnix** [comment]
Alors on a déployé l’arrêt du support des vieux navigateurs le 7 avril :
![screenshot-mcc-2022-05-13-15:20:43,669652145](https://user-images.githubusercontent.com/321872/168293959-1c7a9b62-01d2-4d50-914a-a6da1a3ddb11.png)

Conséquence de ce changement, le JS ne marche plus sur IE11, et la mesure d’audience avec Plausible n’est plus fonctionnelle pour ce navigateur...

**Comment by ronnix** [comment]
Si je fais un rapide examen des logs nginx entre le 4 mai et aujourd’hui, je vois 0,02% d’Internet Explorer, mais dedans il n’y a plus d’IE 11, seulement des très vieux IE 6 à IE 10, ce qui semble valider que la redirection vers Edge fonctionne.

**Comment by rik** [comment]
Quelle était la part de IE11 avant le 7 avril ? Et entre le 7 avril et le 2 mai ?
