### ISSUE TITLE
Infographie « La dose de rappel : pour qui, quand et où ? »

### ISSUE THREAD

**Issue by ronnix** [Delegation-numerique-en-sante/mesconseilscovid#2005]
https://solidarites-sante.gouv.fr/IMG/pdf/infog_rappel.pdf

Mise à jour le 24/01/2022

![image](https://user-images.githubusercontent.com/321872/151710113-68b267b2-cfd9-4ba2-9a68-19fd378f2fa1.png)

**Comment by DuniaAch** [comment]
J'ai du mal à interpréter ces éléments : l'infograhie et les astérix ne disent pas la même chose.
Faut-il comprendre que le vaccin Pfizer est recommandé pour les moins de 30 ans ou bien que le vaccin Moderna est déconseillé (voire qu'on ne peut pas l'utiliser) pour les moins de 30 ans ?
Faut-il enlever les mentions de Moderna dans notre page de conseils pour les mineurs ?

**Comment by ronnix** [comment]
La HAS recommande d’utiliser Pfizer plutôt que Moderna pour les moins de 30 ans. Il me semble qu’en pratique, actuellement, les centres de vaccination ont adapté leur logistique et utilisent systématiquement Pfizer pour les 12-30 ans et Moderna pour les 30+.
