### ISSUE TITLE
DGS-Urgent N°2022-18 (28/01/2022) : Dérogation de passe vaccinal pour les primo-vaccinés

### ISSUE THREAD

**Issue by DuniaAch** [Delegation-numerique-en-sante/mesconseilscovid#2064]
[dgs-u_18_-_derogation_pass_primo-vaccines_v2.pdf](https://github.com/Delegation-numerique-en-sante/mesconseilscovid/files/8040097/dgs-u_18_-_derogation_pass_primo-vaccines_v2.pdf)

>Afin d’inciter les personnes non vaccinées à entamer un cycle de vaccination, depuis le 24 janvier 2022, les personnes de 16 ans ou plus ayant reçu une première injection d’un cycle vaccinal à deux injections peuvent utiliser un test antigénique ou RT-PCR négatif de moins de 24h dans le cadre du passe vaccinal sur le territoire français. Ce système dérogatoire vaut uniquement durant les 28 jours de délai entre la première et la deuxième injection.

>Afin qu’il soit considéré comme valide au titre de passe vaccinal lors d’un contrôle, le certificat de test négatif devra contenir comme information que le patient a bien reçu une première vaccination. 
[...] Si la mention « Dérogation accordée suite à une première injection » n’est pas remplie, le test négatif de moins de 24h ne sera pas considéré comme valide lors du contrôle du passe vaccinal de votre patient

**Comment by ronnix** [comment]
Plus d’actualité depuis la suspension du passe vaccinal.
