### ISSUE TITLE
Gérer la redondance d'information pour les personnes à risque ayant une activité professionnelle

### ISSUE THREAD

**Issue by HelaG** [Delegation-numerique-en-sante/mesconseilscovid#247]
conseils_caractéristiques_antécédents_activité_pro.md et conseils_caractéristiques_antécédents.md sont des contenus très similaires.

La spécificité de conseils_caractéristiques_antécédents_activité_pro.md figure par ailleurs déjà dans conseils_activite_pro.md affichée par ailleurs

Je propose de supprimer conseils_caractéristiques_antécédents_activité_pro.md

**Comment by louis-del** [comment]
J'ai l'impression que conseils_caractéristiques_antécédents_activité_pro.md est le conseil par défaut de la partie vos conseils personnalisés, je ne vois pas s'afficher les conseils conseils_caractéristiques_antécédents.md et je ne vois pas où s'affiche le message conseils_activite_pro.md dans la version actuelle. 
**le conseil *conseils_caractéristiques_antécédents_activité_pro.md* est plus informatif que  *conseils_caractéristiques_antécédents.md*   sur l'incitation au télétravail et le recours à la médecine du travail. Il faudrait transférer ces deux messages dans le conseil *conseils_activite_pro.md*, sous la forme suivante que j'ai exposé dans uen pull request sur l'item conseils_activité_pro.md.**

**Comment by davidbgk** [comment]
@HelaG suite à nos échanges, je pense que l'on peut fermer cette issue ?

**Comment by davidbgk** [comment]
Fait depuis.
