### ISSUE TITLE
Evolution de la doctrine de tests 

### ISSUE THREAD

**Issue by HelaG** [Delegation-numerique-en-sante/mesconseilscovid#250]
Modifier les conseils :
- mesconseilscovid/contenus/conseils/conseils_symptômes_passés_sans_risques.md
- mesconseilscovid/contenus/conseils/conseils_symptômes_passés_avec_risques.md
Et peut-être :
- mesconseilscovid/contenus/conseils/conseils_contact_à_risque.md

**Comment by davidbgk** [comment]
Fait depuis.
