### ISSUE TITLE
Précisions sur browserlist

### ISSUE THREAD

**Issue by busybox11** [Delegation-numerique-en-sante/mesconseilscovid#516]
Bonjour,

J'ai remarqué la présence de `browserlist` dans le `package.json`.
Je ne comprends pas vraiment son utilité, étant donné que les deux seuls "vrais navigateurs" sont Firefox ESR et IE 11.

Faudrait-il rajouter Microsoft Edge, Chrome ? Enlever les autres éléments qui ne sont pas des navigateurs web ?

Merci d'avance et bonne continuation.

**Comment by ronnix** [comment]
Bonjour @busybox11,

Tu trouveras plus d’infos sur les specs browserlist ici : https://github.com/browserslist/browserslist#tools

Certains navigateurs sont listés explicitement (IE11 et Firefox ESR), mais les autres règles permettent de cibler automatiquement les navigateurs les plus courants.

Pour voir la liste complète des navigateurs correspondant aux règles utilisés, tu peux utiliser la commande `npx browserlist` :
```
$ npx browserslist
and_chr 85
and_ff 79
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
chrome 85
chrome 84
chrome 83
chrome 72
chrome 71
chrome 70
edge 85
edge 84
firefox 80
firefox 79
firefox 78
firefox 68
ie 11
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
ios_saf 11.3-11.4
ios_saf 10.3
kaios 2.5
op_mini all
op_mob 46
opera 70
opera 69
safari 13.1
safari 13
samsung 12.0
samsung 11.1-11.2
```

Bonne continuation !

**Comment by ronnix** [comment]
Il n'est pas utile d'ajouter Chrome car il est déjà inclus dans les règles utilisées : navigateurs représentant au moins 0,5% du traffic en France, au moins les deux dernières versions des navigateurs de la liste par défaut.

On n'ajoute explicitement IE11 et la version "ESR" de Firefox que parce que ce sont des navigateurs anciens mais qu'on rencontre encore pas mal dans les entreprises et administrations et que l'on veut être sûrs qu'ils soient pris en compte.

**Comment by busybox11** [comment]
@ronnix Got it, je comprends mieux.

Merci pour l'astuce !
