### ISSUE TITLE
creer un conseil spécifique pour les contact vivant avec la personne malade 

### ISSUE THREAD

**Issue by yann-mael** [Delegation-numerique-en-sante/mesconseilscovid#538]
on a un petit sujet :
quand on vie avec quelqun de malade on doit faire un test tout de suite, puis refaire un test soit si apparition de symtomes soit 7 jours apres la guérisons de la personne malade du foyer. aujourdhui on leur dit de faire un test 7 jours apres le contact conseils_personnels_contact_à_risque.md

il faudrait creer pour les contact a risque qui gievent avec la personne malade un conseil spé

Nous vous conseillons de :
Vous maintenir en isolement.
Appliquer les mesures barrières renforcées avec la personne malade et les autres membres de votre foyer.
Faire un test de dépistage si vous ne l'avez pas déjà fait même en l'absence de symptômes. Si celui ci est négatif vous devez rester en isolement jusqu’à 7 jours après la guérison du cas infecté du foyer et refaire un test à ce moment la. 
==>S’il est négatif, vous pourrez lever votre isolement.
==>Si le test est positif, il faudra à nouveau 7 jours d’isolement, et surveiller l’apparition de symptômes.
Si vous constatez l’apparition de symptômes, contactez votre médecin, et suivez leur évolution avec le questionnaire de suivi.
Revenir sur Mes Conseils Covid si votre situation change afin d’avoir les conseils adaptés à votre nouvelle situation !

**Comment by davidbgk** [comment]
En cours d'implémentation ici https://github.com/Delegation-numerique-en-sante/mesconseilscovid/pull/542
