### ISSUE TITLE
[WIP] Créer 3 conseils différents en fonction de la raison pour laquelle je suis en isolement

### ISSUE THREAD

**Issue by HelaG** [Delegation-numerique-en-sante/mesconseilscovid#539]
isolement-symptômes.md - si symptômes et pas de test
isolement-test-positif.md - si test positif
isolement-cas-contact.md - si contact à risque dans les 7 derniers jours. 

Et ajouter une distinction entre l'isolement et le confinement ?

**Comment by davidbgk** [comment]
Sur https://github.com/Delegation-numerique-en-sante/mesconseilscovid/blob/master/contenus/conseils/conseils_isolement.md

Personnaliser la partie :

> au minimum 7 jours après le début des symptômes, du test positif, ou du dernier contact à risque avec un malade,
