### ISSUE TITLE
readme contenu anomalie?

### ISSUE THREAD

**Issue by yann-mael** [Delegation-numerique-en-sante/mesconseilscovid#71]
Dans le readme contenu, je ne vois plus apparaître le Conseils_isolement.md https://github.com/Delegation-numerique-en-sante/mesconseilscovid/blob/master/contenus/conseils/conseils_isolement.md

Pourtant il apparaît bien sur le site internet

**Comment by davidbgk** [comment]
@yann-mael bien vu, c'est corrigé !
